### ISSUE TITLE
Installation with pip on 64-bit Windows 10 with Python 2.7 doesn't work

### ISSUE THREAD

**Issue by themrdjj** [SCIP-Interfaces/PySCIPOpt#102]
I just tried installing PySCIPOpt with pip by doing "pip install pyscipopt", however I get the following error message:

`Collecting pyscipopt
  Using cached PySCIPOpt-1.2.0.tar.gz
Building wheels for collected packages: pyscipopt
  Running setup.py bdist_wheel for pyscipopt ... error
  Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\daniel\\appdata\\local\\temp\\pip-build-kejfxp\\pyscipopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\daniel\appdata\local\temp\tmpaj_ydopip-wheel- --python-tag cp27:
  scipoptir:
  includedir: c:\users\daniel\appdata\local\temp\pip-build-kejfxp\pyscipopt\include
  libdir: c:\users\daniel\appdata\local\temp\pip-build-kejfxp\pyscipopt\lib
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-2.7
  creating build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\Multidict.py -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\__init__.py -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\scip.pyx -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\scip.pxd -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\branchrule.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\conshdlr.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\expr.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\heuristic.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\lp.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\presol.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\pricer.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\propagator.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\sepa.pxi -> build\lib.win32-2.7\pyscipopt
  running build_ext
  building 'pyscipopt.scip' extension
  creating build\temp.win32-2.7
  creating build\temp.win32-2.7\Release
  creating build\temp.win32-2.7\Release\src
  creating build\temp.win32-2.7\Release\src\pyscipopt
  C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\users\daniel\appdata\local\temp\pip-build-kejfxp\pyscipopt\include -IC:\Python27\include -IC:\Python27\PC /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win32-2.7\Release\src\pyscipopt\scip.obj
  scip.c
  src\pyscipopt\scip.c(507) : fatal error C1083: Cannot open include file: 'scip/scip.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for pyscipopt
  Running setup.py clean for pyscipopt
Failed to build pyscipopt
Installing collected packages: pyscipopt
  Running setup.py install for pyscipopt ... error
    Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\daniel\\appdata\\local\\temp\\pip-build-kejfxp\\pyscipopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\daniel\appdata\local\temp\pip-zqfl67-record\install-record.txt --single-version-externally-managed --compile:
    scipoptir:
    includedir: c:\users\daniel\appdata\local\temp\pip-build-kejfxp\pyscipopt\include
    libdir: c:\users\daniel\appdata\local\temp\pip-build-kejfxp\pyscipopt\lib
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\Multidict.py -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\__init__.py -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\scip.pyx -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\scip.pxd -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\branchrule.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\conshdlr.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\expr.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\heuristic.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\lp.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\presol.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\pricer.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\propagator.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\sepa.pxi -> build\lib.win32-2.7\pyscipopt
    running build_ext
    building 'pyscipopt.scip' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\src
    creating build\temp.win32-2.7\Release\src\pyscipopt
    C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\users\daniel\appdata\local\temp\pip-build-kejfxp\pyscipopt\include -IC:\Python27\include -IC:\Python27\PC /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win32-2.7\Release\src\pyscipopt\scip.obj
    scip.c
    src\pyscipopt\scip.c(507) : fatal error C1083: Cannot open include file: 'scip/scip.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\daniel\\appdata\\local\\temp\\pip-build-kejfxp\\pyscipopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\daniel\appdata\local\temp\pip-zqfl67-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\daniel\appdata\local\temp\pip-build-kejfxp\pyscipopt\`

Am I doing something wrong?

**Comment by mattmilten** [comment]
Yes, you are :-)

Apparently, you're missing the SCIP headers. Did you install the SCIPOptSuite beforehand? Please have another look at the INSTALL file.

**Comment by themrdjj** [comment]
Hmm alright, so I just installed the SCIPOptSuite (using the installer) and as mentioned in the Install document I typed the following into cmd:
`
set SCIPOPTDIR=C:\Program Files\SCIPOptSuite 4.0.1`

There is a folder called "include" in the same directory as "lib", so I assume that the headers are present? (not that I have any idea what those are)

**Comment by mattmilten** [comment]
Yeah, so what? Did it work now? Was there some other error message? You need to run pip install again.

**Comment by themrdjj** [comment]
Oh right, sorry, I forgot to mention that it still didn't work. Of course I ran pip install again.

Here's the error message, I think it's still the same?

```
Collecting pyscipopt
  Using cached PySCIPOpt-1.2.0.tar.gz
Building wheels for collected packages: pyscipopt
  Running setup.py bdist_wheel for pyscipopt ... error
  Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\daniel\\appdata\\local\\temp\\pip-build-wlkg3c\\pyscipopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d c:\users\daniel\appdata\local\temp\tmppoak3dpip-wheel- --python-tag cp27:
  scipoptir:
  includedir: c:\users\daniel\appdata\local\temp\pip-build-wlkg3c\pyscipopt\include
  libdir: c:\users\daniel\appdata\local\temp\pip-build-wlkg3c\pyscipopt\lib
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-2.7
  creating build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\Multidict.py -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\__init__.py -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\scip.pyx -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\scip.pxd -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\branchrule.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\conshdlr.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\expr.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\heuristic.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\lp.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\presol.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\pricer.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\propagator.pxi -> build\lib.win32-2.7\pyscipopt
  copying src\pyscipopt\sepa.pxi -> build\lib.win32-2.7\pyscipopt
  running build_ext
  building 'pyscipopt.scip' extension
  creating build\temp.win32-2.7
  creating build\temp.win32-2.7\Release
  creating build\temp.win32-2.7\Release\src
  creating build\temp.win32-2.7\Release\src\pyscipopt
  C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\users\daniel\appdata\local\temp\pip-build-wlkg3c\pyscipopt\include -IC:\Python27\include -IC:\Python27\PC /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win32-2.7\Release\src\pyscipopt\scip.obj
  scip.c
  src\pyscipopt\scip.c(507) : fatal error C1083: Cannot open include file: 'scip/scip.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for pyscipopt
  Running setup.py clean for pyscipopt
Failed to build pyscipopt
Installing collected packages: pyscipopt
  Running setup.py install for pyscipopt ... error
    Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\daniel\\appdata\\local\\temp\\pip-build-wlkg3c\\pyscipopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\daniel\appdata\local\temp\pip-orx5t4-record\install-record.txt --single-version-externally-managed --compile:
    scipoptir:
    includedir: c:\users\daniel\appdata\local\temp\pip-build-wlkg3c\pyscipopt\include
    libdir: c:\users\daniel\appdata\local\temp\pip-build-wlkg3c\pyscipopt\lib
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\Multidict.py -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\__init__.py -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\scip.pyx -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\scip.pxd -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\branchrule.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\conshdlr.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\expr.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\heuristic.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\lp.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\presol.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\pricer.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\propagator.pxi -> build\lib.win32-2.7\pyscipopt
    copying src\pyscipopt\sepa.pxi -> build\lib.win32-2.7\pyscipopt
    running build_ext
    building 'pyscipopt.scip' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\src
    creating build\temp.win32-2.7\Release\src\pyscipopt
    C:\Program Files (x86)\Common Files\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\users\daniel\appdata\local\temp\pip-build-wlkg3c\pyscipopt\include -IC:\Python27\include -IC:\Python27\PC /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win32-2.7\Release\src\pyscipopt\scip.obj
    scip.c
    src\pyscipopt\scip.c(507) : fatal error C1083: Cannot open include file: 'scip/scip.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Common Files\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\daniel\\appdata\\local\\temp\\pip-build-wlkg3c\\pyscipopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\daniel\appdata\local\temp\pip-orx5t4-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\daniel\appdata\local\temp\pip-build-wlkg3c\pyscipopt\
```

**Comment by mattmilten** [comment]
You didn't set the SCIPOPTDIR environment variable as is written here: https://github.com/SCIP-Interfaces/PySCIPOpt/blob/master/INSTALL.rst#requirements

**Comment by themrdjj** [comment]
So that should be something like this? 

`set SCIPOPTDIR=C:\Program Files`

SCIPOptSuite is installed is installed there. I tried entering that in the cmd, doesn't work either.

**Comment by mattmilten** [comment]
No. It's 

    set SCIPOPTDIR="C:\Program Files\SCIPOptSuite"

Doesn't it say in the INSTALL.rst, that this is the directory that needs to contain among others a `lib` with the `scip.lib`? Please read the docs carefully.

**Comment by mt5100625** [comment]
I followed the following procedure:

1. Installed SCIPOptSuite-4.0.1-win64.exe. It created a folder at location "C:\Program Files\SCIPOptSuite 4.0.1" with bin, include, lib as sub folders. note: lib folder has files like scip.lib, soplex.lib etc
2. Installed visual studio community 2017 edition for windows.
3. Installed Microsoft Visual C++ Compiler for Python 2.7
4. set the SCIPOPTDIR variable in environmental variables as "C:\Program Files\SCIPOptSuite 4.0.1\"
5. also added the above path in PATH variable.

i got the following error

```
C:\Users\nei6kor>pip install pyscipopt
Collecting pyscipopt
  Using cached PySCIPOpt-1.2.0.tar.gz
Building wheels for collected packages: pyscipopt
  Running setup.py bdist_wheel for pyscipopt
  Complete output from command c:\python27_64\python.exe -c "import setuptools;__file__='c:\\users\\nei6kor\\appdata\\local\\temp\\pip-build-wdgziz\\pyscipopt\\
setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\nei6kor\appdata\local\temp\tmpjqrqc1pip-wheel-:
  scipoptir: C:\Program Files\SCIPOptSuite 4.0.1
  includedir: C:\Program Files\SCIPOptSuite 4.0.1\include
  libdir: C:\Program Files\SCIPOptSuite 4.0.1\lib
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\Multidict.py -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\__init__.py -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\scip.pyx -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\scip.pxd -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\branchrule.pxi -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\conshdlr.pxi -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\expr.pxi -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\heuristic.pxi -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\lp.pxi -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\presol.pxi -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\pricer.pxi -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\propagator.pxi -> build\lib.win-amd64-2.7\pyscipopt
  copying src\pyscipopt\sepa.pxi -> build\lib.win-amd64-2.7\pyscipopt
  running build_ext
  building 'pyscipopt.scip' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\src
  creating build\temp.win-amd64-2.7\Release\src\pyscipopt
  C:\Users\nei6kor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program File
s\SCIPOptSuite 4.0.1\include" -Ic:\python27_64\include -Ic:\python27_64\PC /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win-amd64-2.7\Release\src\pyscipopt\scip.obj
  scip.c
  C:\Program Files\SCIPOptSuite 4.0.1\include\scip/def.h(32) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
  error: command 'C:\\Users\\nei6kor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2


  ----------------------------------------
  Failed building wheel for pyscipopt
Failed to build pyscipopt
Installing collected packages: pyscipopt
  Running setup.py install for pyscipopt
    Complete output from command c:\python27_64\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\nei6kor\\appdata\\local\\temp\\pip-build-wdgziz\
\pyscipopt\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\nei6kor
\appdata\local\temp\pip-rlyszs-record\install-record.txt --single-version-externally-managed --compile:
    scipoptir: C:\Program Files\SCIPOptSuite 4.0.1
    includedir: C:\Program Files\SCIPOptSuite 4.0.1\include
    libdir: C:\Program Files\SCIPOptSuite 4.0.1\lib
    running install
    running build
    running build_py
    running build_ext
    building 'pyscipopt.scip' extension
    C:\Users\nei6kor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG "-IC:\Program Fi
les\SCIPOptSuite 4.0.1\include" -Ic:\python27_64\include -Ic:\python27_64\PC /Tcsrc\pyscipopt\scip.c /Fobuild\temp.win-amd64-2.7\Release\src\pyscipopt\scip.obj
    scip.c
    C:\Program Files\SCIPOptSuite 4.0.1\include\scip/def.h(32) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    error: command 'C:\\Users\\nei6kor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status
 2

    ----------------------------------------
Command "c:\python27_64\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\nei6kor\\appdata\\local\\temp\\pip-build-wdgziz\\pyscipopt\\setup.py';ex
ec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\nei6kor\appdata\local\temp\pip-
rlyszs-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\nei6kor\appdata\local\temp\pip-build-wdgziz
\pyscipopt

```

i have read all possible answers from stackoverflow (https://stackoverflow.com/questions/12970293/why-microsoft-visual-studio-cannot-find-stdint-h) and on github (https://github.com/SCIP-Interfaces/PySCIPOpt/issues/36), couldn't figure out why i'm getting this error, please help

**Comment by mattmilten** [comment]
Did this solve the issue?

**Comment by mt5100625** [comment]
Yes it solved.. installation is done... hope no errors while executing the codes :)

**Comment by OscarVM** [comment]
Hello.

I tried the installation of pyscipopt on python 2.7 ,32bit on the anaconda distribution. My computer is 64bit but for other applications i started using the 32 bit distribution. The SCIP version downloaded was 4.01 32 b.

The procedure i followed was:
-Install visual c++ for python 2.7
-Install SCIPopt Suite 4.01 from the executable.
-Create  "SCIPOPTDIR= C:\Program Files\SCIPOptSuite 4.0.1" where  lib folder(with scip.lib) and include folders are.
-Append in PATH,+ %SCIPOPTDIR%\bin
-Run from the visual C++ command prompt vcvarsall.
-Update setuptools and pip in anaconda from anaconda prompt. 
-Incluide the stdin.h file on the incluide files.
-Install via pip pyscipopt via anaconda prompt. It is installed correctly and finishes installing.

but..
When running an optimization file on Spyder I have  got the error showing that "vcvarsall" was not to be found.

```
runfile('C:/Users/INES/Dropbox/Oscar/Final_Versions/MILP Testing/KWKK_MILP_SCIP.py', wdir='C:/Users/INES/Dropbox/Oscar/Final_Versions/MILP Testing')
Traceback (most recent call last):

  File "<ipython-input-1-560f31406914>", line 1, in <module>
    runfile('C:/Users/INES/Dropbox/Oscar/Final_Versions/MILP Testing/KWKK_MILP_SCIP.py', wdir='C:/Users/INES/Dropbox/Oscar/Final_Versions/MILP Testing')

  File "C:\Users\INES\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\INES\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/INES/Dropbox/Oscar/Final_Versions/MILP Testing/KWKK_MILP_SCIP.py", line 17, in <module>
    from pyscipopt import Model, quicksum

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyscipopt\__init__.py", line 5, in <module>
    from pyscipopt.scip      import Model

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyximport\pyximport.py", line 445, in load_module
    language_level=self.language_level)

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyximport\pyximport.py", line 234, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyximport\pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyximport\pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()

  File "C:\Users\INES\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)

  File "C:\Users\INES\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()

  File "C:\Users\INES\Anaconda2\lib\site-packages\Cython\Distutils\old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)

  File "C:\Users\INES\Anaconda2\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()

  File "C:\Users\INES\Anaconda2\lib\site-packages\Cython\Distutils\old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)

  File "C:\Users\INES\Anaconda2\lib\distutils\command\build_ext.py", line 499, in build_extension
    depends=ext.depends)

  File "C:\Users\INES\Anaconda2\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()

  File "C:\Users\INES\Anaconda2\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)

  File "C:\Users\INES\Anaconda2\lib\distutils\msvc9compiler.py", line 271, in query_vcvarsall
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")

ImportError: Building module pyscipopt.scip failed: ['DistutilsPlatformError: Unable to find vcvarsall.bat\n']
```

I tried different ways but the only one that seemed to change something was via this workaround modifying the msvc9compiler.py file.

`def find_vcvarsall(version):
    productdir= "C:/Users/UserName/AppData/Local/Programs/Common/Microsoft/Visual C++ for Python/9.0"
    vcvarsall = os.path.join(productdir, "vcvarsall.bat")
    if os.path.isfile(vcvarsall):
        return vcvarsall
    else:
        return None`

There it seems to remove the vcvarsall error but trying to run again it shows the following:
```
runfile('C:/Users/INES/Dropbox/Oscar/Final_Versions/MILP Testing/KWKK_MILP_SCIP.py', wdir='C:/Users/INES/Dropbox/Oscar/Final_Versions/MILP Testing')
Traceback (most recent call last):

  File "<ipython-input-1-560f31406914>", line 1, in <module>
    runfile('C:/Users/INES/Dropbox/Oscar/Final_Versions/MILP Testing/KWKK_MILP_SCIP.py', wdir='C:/Users/INES/Dropbox/Oscar/Final_Versions/MILP Testing')

  File "C:\Users\INES\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\INES\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/INES/Dropbox/Oscar/Final_Versions/MILP Testing/KWKK_MILP_SCIP.py", line 17, in <module>
    from pyscipopt import Model, quicksum

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyscipopt\__init__.py", line 5, in <module>
    from pyscipopt.scip      import Model

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyximport\pyximport.py", line 445, in load_module
    language_level=self.language_level)

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyximport\pyximport.py", line 234, in load_module
    exec("raise exc, None, tb", {'exc': exc, 'tb': tb})

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyximport\pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyximport\pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)

  File "C:\Users\INES\Anaconda2\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()

  File "C:\Users\INES\Anaconda2\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)

  File "C:\Users\INES\Anaconda2\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()

  File "C:\Users\INES\Anaconda2\lib\site-packages\Cython\Distutils\old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)

  File "C:\Users\INES\Anaconda2\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()

  File "C:\Users\INES\Anaconda2\lib\site-packages\Cython\Distutils\old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)

  File "C:\Users\INES\Anaconda2\lib\distutils\command\build_ext.py", line 499, in build_extension
    depends=ext.depends)

  File "C:\Users\INES\Anaconda2\lib\distutils\msvc9compiler.py", line 558, in compile
    raise CompileError(msg)

ImportError: Building module pyscipopt.scip failed: ["CompileError: command 'C:\\\\Users\\\\INES\\\\AppData\\\\Local\\\\Programs\\\\Common\\\\Microsoft\\\\Visual C++ for Python\\\\9.0\\\\VC\\\\Bin\\\\cl.exe' failed with exit status 2\n"]
```

Might i be doing something wrong, or what could be possibly the cause of these errors.

**Comment by siddhardha8788** [comment]
Hi All, 

I'm also facing the same issue , 
could you please suggest me the steps how to resolve this issue

16:53:31 copying psutil\tests\__init__.py -> build\lib.win32-2.7\psutil\tests
16:53:31 copying psutil\tests\__main__.py -> build\lib.win32-2.7\psutil\tests
16:53:31 running build_ext
16:53:31 building 'psutil._psutil_windows' extension
16:53:31 d:\slave\workspace\DES-DMF_metagen_build_win\work\envs\_build\lib\distutils\dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
16:53:31   warnings.warn(msg)
16:53:31 error: Setup script exited with error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get it from http://aka.ms/vcpython27
16:53:31
