### ISSUE TITLE
import issue for mac osx 

### ISSUE THREAD

**Issue by LingxiaoShawn** [SCIP-Interfaces/PySCIPOpt#146]
I install the package according to the description. It works well but when I import it in python, the error goes out:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/envs/py3.5/lib/python3.5/site-packages/pyscipopt/__init__.py", line 5, in <module>
    from pyscipopt.scip      import Model
ImportError: dlopen(//anaconda/envs/py3.5/lib/python3.5/site-packages/pyscipopt/scip.cpython-35m-darwin.so, 2): Library not loaded: libscip.5.0.dylib
  Referenced from: //anaconda/envs/py3.5/lib/python3.5/site-packages/pyscipopt/scip.cpython-35m-darwin.so
  Reason: image not found

**Comment by LingxiaoShawn** [comment]
Sorry I figured out:

Just put the lib folder into path:

 export DYLD_LIBRARY_PATH=/path/to/scip/lib:$DYLD_LIBRARY_PAT
