### ISSUE TITLE
Issue with 'SCIP: the parameter

### ISSUE THREAD

**Issue by yzy1996** [SCIP-Interfaces/PySCIPOpt#329]
Windows10

I have installed SCIP and pyscipopt successfully. But I met the problem which I can not find the answer. I wondered that whether I should install SoPlex separately.

`[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.2\scip\src\scip\paramset.c:2001] ERROR: parameter <branching/vanillafullstrong/integralcands> unknown
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.2\scip\src\scip\set.c:3086] ERROR: Error <-12> in function call
[C:\Jenkins\workspace\SCIPOptSuite_windows_libs_release\scipoptsuite-6.0.2\scip\src\scip\scip_param.c:447] ERROR: Error <-12> in function call
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\zhiyuyang4\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\zhiyuyang4\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zhiyuyang4\OneDrive - City University of Hong Kong\Github\Download\learn2branch_group_huilingzhen\02_generate_dataset_mip.py", line 133, in make_samples
    m.setBoolParam('branching/vanillafullstrong/integralcands', True)
  File "src/pyscipopt/scip.pyx", line 3874, in pyscipopt.scip.Model.setBoolParam
  File "src/pyscipopt/scip.pyx", line 243, in pyscipopt.scip.PY_SCIP_CALL
KeyError: 'SCIP: the parameter with the given name was not found!'`

**Comment by yzy1996** [comment]
I have solved this problem.

**Comment by mtldsw** [comment]
hello I have the same problem, can you give your solution?

**Comment by fserra** [comment]
the problem above was trying to set the parameter `branching/vanillafullstrong/integralcands`. However that parameter does not exist in scip 6.0.2
so you need to upgrade to scip 7

**Comment by yzy1996** [comment]
Agree with @fserra. And I solve this problem following the installing steps by learn2branch.

**Comment by yzy1996** [comment]
Agree with @fserra. And I solve this problem following the installation steps by learn2branch.

**Comment by fserra** [comment]
oh, but now the vanilla strong branching is included in scip7, so it should work out of the box
