### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'ptrtuple'

### ISSUE THREAD

**Issue by HJarausch** [SCIP-Interfaces/PySCIPOpt#34]
python test_tsp.py     # this is from the test suite
Traceback (most recent call last):
  File "test_tsp.py", line 116, in <module>
    test_main()
  File "test_tsp.py", line 110, in test_main
    objective_value, edges = solve_tsp(vertices, distance)
  File "test_tsp.py", line 88, in solve_tsp
    model, x = create_tsp(vertices, distance)
  File "test_tsp.py", line 83, in create_tsp
    "minimize")
  File "pyscipopt/scip.pyx", line 442, in pyscipopt.scip.Model.setObjective (pyscipopt/scip.c:38864)
  File "pyscipopt/expr.pxi", line 55, in pyscipopt.scip.Term.__eq__ (pyscipopt/scip.c:4904)
AttributeError: 'tuple' object has no attribute 'ptrtuple'

This occurs with the GIT version of PySCIPOpt used with Python 3.5.2

File "test_tsp.py", line 83, in create_tsp is this statement:

  model.setObjective(
    quicksum(distance[i,j] * x[i,j] for (i,j) in pairs(vertices)),
    "minimize")

File "pyscipopt/expr.pxi", line 55 is this statement:

    def __eq__(self, other):
        return self.ptrtuple == other.ptrtuple
where "other" is an (ordinary) tuple

**Comment by leethargo** [comment]
Thanks for the report.
