### ISSUE TITLE
pyscipopt DLL Error

### ISSUE THREAD

**Issue by MutadisMutandis** [SCIP-Interfaces/PySCIPOpt#415]
Hello everyone

I'm using "spyder". I want to work with "pyscipopt" module. I imported the module as "pip install pyscipopt". but when I run the module I get the following error.
-------------------------------------------------------------------------------------------------------------------------------
runfile('C:/Users/OemPC/.spyder-py3/Numpy_Exercise/untitled0.py')
Traceback (most recent call last):

  File "C:\Users\OemPC\.spyder-py3\Numpy_Exercise\untitled0.py", line 1, in <module>
    import pyscipopt

  File "C:\Anaconda\lib\site-packages\pyscipopt\__init__.py", line 10, in <module>
    from pyscipopt.scip      import Model

ImportError: DLL load failed: Belirtilen modül bulunamadı.
--------------------------------------------------------------------------------------------------------------------

The file path of the "pyscipopt" module on my computer is "C: \ Anaconda \ Lib \ site-packages \ pyscipopt". And this file contains the following documents.

> __pycache__
                 __init__.cpython-37
                 Multidict.cpython-37
> __init__
> benders.pxi
> benderscut.pxi
> branchrule.pxiconshdlr.pxi
> event.pxi
> expr.pxi 
> etc........

I think I need to make changes to this file path or a document within the file. But I couldn't understand what to do.

I will be grateful if you could help me.

**Comment by MutadisMutandis** [comment]
I İnstalled the "SCIPOptSuite-7.0.1-win64-VS15.exe" from "https://www.scipopt.org/index.php#download"  and problem has been solved. 
Thank you very much...
