### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by Benezivas** [SCIP-Interfaces/PySCIPOpt#96]
Hello,
I installed scip-4.0.1 and the current PySCIPOpt version from source, built Scip using 
`make install INSTALLDIR=/home/henri/sciptest SHARED=true -j GMP=false READLINE=false`
without any errors or warnings, set the enviroment variable SCIPOPTDIR accordingly in my .zprofile and built PySCIPOpt using `python setup.py install`, output:
```
running install
running bdist_egg
running egg_info
writing PySCIPOpt.egg-info/PKG-INFO
writing dependency_links to PySCIPOpt.egg-info/dependency_links.txt
writing top-level names to PySCIPOpt.egg-info/top_level.txt
reading manifest file 'PySCIPOpt.egg-info/SOURCES.txt'
writing manifest file 'PySCIPOpt.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'pyscipopt.scip' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/home/henri/scip/include -I/usr/include/python3.6m -c src/pyscipopt/scip.c -o build/temp.linux-x86_64-3.6/src/pyscipopt/scip.o
gcc -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-3.6/src/pyscipopt/scip.o -L/home/henri/scip/lib -L/usr/lib -Wl,--enable-new-dtags,-R/home/henri/scip/lib -lscip -lpython3.6m -o build/lib.linux-x86_64-3.6/pyscipopt/scip.cpython-36m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/conshdlr.pxi -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/pricer.pxi -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/sepa.pxi -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/branchrule.pxi -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/__init__.py -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/lp.pxi -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/propagator.pxi -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/scip.pxd -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/presol.pxi -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/heuristic.pxi -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/scip.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/Multidict.py -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/expr.pxi -> build/bdist.linux-x86_64/egg/pyscipopt
copying build/lib.linux-x86_64-3.6/pyscipopt/scip.pyx -> build/bdist.linux-x86_64/egg/pyscipopt
byte-compiling build/bdist.linux-x86_64/egg/pyscipopt/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyscipopt/Multidict.py to Multidict.cpython-36.pyc
creating stub loader for pyscipopt/scip.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/pyscipopt/scip.py to scip.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying PySCIPOpt.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PySCIPOpt.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PySCIPOpt.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying PySCIPOpt.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
pyscipopt.__pycache__.scip.cpython-36: module references __file__
creating dist
creating 'dist/PySCIPOpt-1.2.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing PySCIPOpt-1.2.0-py3.6-linux-x86_64.egg
creating /usr/lib/python3.6/site-packages/PySCIPOpt-1.2.0-py3.6-linux-x86_64.egg
Extracting PySCIPOpt-1.2.0-py3.6-linux-x86_64.egg to /usr/lib/python3.6/site-packages
Adding PySCIPOpt 1.2.0 to easy-install.pth file

Installed /usr/lib/python3.6/site-packages/PySCIPOpt-1.2.0-py3.6-linux-x86_64.egg
Processing dependencies for PySCIPOpt==1.2.0
Finished processing dependencies for PySCIPOpt==1.2.0
```
If I know try to use PySCIPOpt in my code as suggested with `from pyscipopt import Model` I get the following error:
``` 
~ python scipSolve.py 
Traceback (most recent call last):
  File "scipSolve.py", line 1, in <module>
    from pyscipopt import Model
  File "/usr/lib/python3.6/site-packages/PySCIPOpt-1.2.0-py3.6-linux-x86_64.egg/pyscipopt/__init__.py", line 3, in <module>
    from pyscipopt.scip      import Model
ImportError: /home/henri/scip/lib/libscip.so: undefined symbol: SCIPnlpiComp
```
Any ideas? The folder structure in /home/henri/scip is as the INSTALL.rst suggests.

SCIP 4.0.1
Python 3.6
Cython 0.27.1
gcc 7.2.0

**Comment by mattmilten** [comment]
You can either use CMake to generate the correct libscip.so or you run "make scipsolver" and rename or link the resulting linscipsolver lib to libscip.so.

If you're using the SCIP Optimization Suite you can also run "make scipoptlib" and rename the resulting lib to libscip.so. 

Please excuse the complications. We reorganized the SCIP build system and CMake is now the recommended way for building the lib for PySCIPOpt.

**Comment by Benezivas** [comment]
Thank you very much for your answer, I ran `make scipoptlib GMP=false READLINE=false -j`
and symlinked the resulting lib. 
Importing now works as intended.
